## Data Manipulation Techniques

Data manipulation techniques are essential for preparing and transforming data for analysis. These techniques can help clean, organize, and structure data to make it more suitable for analysis. Below are some common data manipulation techniques:

### 1. Data Cleaning
Data cleaning involves identifying and correcting errors or inconsistencies in the data. This may include handling missing values, removing duplicates, and correcting data types. Common methods for data cleaning include:
- **Handling Missing Values**: Techniques such as imputation, deletion, or using algorithms that can handle missing data.
- **Removing Duplicates**: Identifying and removing duplicate records to ensure data integrity.
- **Correcting Data Types**: Ensuring that data is in the correct format (e.g., converting strings to dates or numbers).
### 2. Data Transformation
Data transformation involves changing the format, structure, or values of data to make it more suitable for analysis. This can include normalization, scaling, and encoding categorical variables. Common methods for data transformation include:
- **Normalization**: Adjusting the scale of data to a standard range, often between 0 and 1.
- **Scaling**: Rescaling data to have a specific mean and standard deviation, often used in machine learning algorithms.
- **Encoding Categorical Variables**: Converting categorical data into numerical format using techniques like one-hot encoding or label encoding.
### 3. Data Aggregation
Data aggregation involves summarizing data to provide insights or to prepare it for analysis. This can include grouping data by specific attributes and calculating summary statistics. Common methods for data aggregation include:
- **Grouping**: Organizing data into groups based on specific attributes (e.g., grouping sales data by region).
- **Calculating Summary Statistics**: Computing measures such as mean, median, sum, and count for each group to gain insights into the data.
### 4. Data Merging and Joining
Data merging and joining involve combining multiple datasets into a single dataset based on common attributes. This is useful for integrating data from different sources. Common methods for data merging and joining include:
- **Inner Join**: Combining datasets where only matching records from both datasets are included.
- **Outer Join**: Combining datasets where all records from both datasets are included, with missing values filled in where there is no match.
- **Left Join**: Combining datasets where all records from the left dataset are included, and matching records from the right dataset are added.
- **Right Join**: Combining datasets where all records from the right dataset are included, and matching records from the left dataset are added.

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('sd.csv')

## fetch the first 5 rows of the data
df.head(5)

## Fetch the last 5 rows of the data
df.tail(5)

,OrderDate,Category,City,Country,CustomerName,Discount,OrderID,PostalCode,ProductName,Profit,...,DaystoShipActual,SalesForecast,ShipStatus,DaystoShipScheduled,OrderProfitable,SalesperCustomer,ProfitRatio,SalesaboveTarget,latitude,longitude
9989,2014-12-31T00:00:00.000Z,Office Supplies,Fairfield,United States,Erica Bern,0.2,CA-2014-115427,94533,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",5,...,4,18,Shipped Early,6,NaN,13.90,32.5,NaN,38.2671,-122.0357
9990,2014-12-31T00:00:00.000Z,Office Supplies,Fairfield,United States,Erica Bern,0.2,CA-2014-115427,94533,GBC Binding covers,6,...,4,27,Shipped Early,6,NaN,20.72,31.3,NaN,38.2671,-122.0357
9991,2014-12-31T00:00:00.000Z,Office Supplies,Loveland,United States,Jill Matthias,0.2,CA-2014-156720,80538,Bagged Rubber Bands,-1,...,4,4,Shipped Early,6,NaN,3.02,-20.0,NaN,40.4262,-105.0900
9992,2014-12-31T00:00:00.000Z,Office Supplies,New York City,United States,Patrick ODonnell,0.2,CA-2014-143259,10009,Wilson Jones Legal Size Ring Binders,20,...,4,69,Shipped Early,6,NaN,52.78,37.5,NaN,40.7262,-73.9796
9993,2014-12-31T00:00:00.000Z,Technology,New York City,United States,Patrick ODonnell,0.0,CA-2014-143259,10009,Gear Head AU3700S Headset,3,...,4,119,Shipped Early,6,NaN,90.93,3.0,NaN,40.7262,-73.9796

In [4]:
df.describe()

,Discount,PostalCode,Profit,Quantity,Sales,DaystoShipActual,SalesForecast,DaystoShipScheduled,OrderProfitable,SalesperCustomer,ProfitRatio,SalesaboveTarget,latitude,longitude
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,0.0,9994.000000,9994.000000,0.0,9994.000000,9994.000000
mean,0.156203,55190.379428,28.651891,3.789574,229.873324,3.958875,301.200620,4.320692,NaN,229.857992,12.037092,NaN,37.787222,-94.360212
std,0.206452,32063.693350,234.255712,2.225110,623.248946,1.747097,816.700059,2.176059,NaN,623.245119,46.677878,NaN,4.884539,18.058618
min,0.000000,1040.000000,-6600.000000,1.000000,0.000000,0.000000,1.000000,0.000000,NaN,0.440000,-275.000000,NaN,25.476600,-123.099800
25%,0.000000,23223.000000,2.000000,2.000000,17.000000,3.000000,23.000000,3.000000,NaN,17.280000,7.500000,NaN,34.011600,-117.252100
50%,0.200000,56430.500000,9.000000,3.000000,54.500000,4.000000,71.000000,6.000000,NaN,54.490000,27.000000,NaN,38.790200,-87.761150
75%,0.200000,90008.000000,29.000000,5.000000,210.000000,5.000000,275.000000,6.000000,NaN,209.940000,36.300000,NaN,40.801100,-77.394800
max,0.800000,99301.000000,8400.000000,14.000000,22638.000000,7.000000,29665.000000,6.000000,NaN,22638.480000,50.000000,NaN,48.797400,-68.791800

In [5]:
df.dtypes # It will show the data type of each column in the dataset

OrderDate                  str
Category                   str
City                       str
Country                    str
CustomerName               str
Discount               float64
OrderID                    str
PostalCode               int64
ProductName                str
Profit                   int64
Quantity                 int64
Region                     str
Sales                    int64
Segment                    str
ShipDate                   str
ShipMode                   str
State                      str
Sub_Category               str
DaystoShipActual         int64
SalesForecast            int64
ShipStatus                 str
DaystoShipScheduled      int64
OrderProfitable        float64
SalesperCustomer       float64
ProfitRatio            float64
SalesaboveTarget       float64
latitude               float64
longitude              float64
dtype: object

In [10]:
# Handling missing values

df.isnull()# It will show the columns which have missing values

,OrderDate,Category,City,Country,CustomerName,Discount,OrderID,PostalCode,ProductName,Profit,...,DaystoShipActual,SalesForecast,ShipStatus,DaystoShipScheduled,OrderProfitable,SalesperCustomer,ProfitRatio,SalesaboveTarget,latitude,longitude
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
9990,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
9991,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
9992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
9993,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False

In [18]:
df.isnull().sum() # It will show the total number of missing values in each column

OrderDate                 0
Category                  0
City                      0
Country                   0
CustomerName              0
Discount                  0
OrderID                   0
PostalCode                0
ProductName               0
Profit                    0
Quantity                  0
Region                    0
Sales                     0
Segment                   0
ShipDate                  0
ShipMode                  0
State                     0
Sub_Category              0
DaystoShipActual          0
SalesForecast             0
ShipStatus                0
DaystoShipScheduled       0
OrderProfitable        9994
SalesperCustomer          0
ProfitRatio               0
SalesaboveTarget       9994
latitude                  0
longitude                 0
dtype: int64

In [14]:
df_filled=df.fillna(0) # It will fill the missing values with 0
print(df_filled)

                     OrderDate         Category           City        Country  \
0     2011-01-04T00:00:00.000Z  Office Supplies        Houston  United States
1     2011-01-05T00:00:00.000Z  Office Supplies     Naperville  United States
2     2011-01-05T00:00:00.000Z  Office Supplies     Naperville  United States
3     2011-01-05T00:00:00.000Z  Office Supplies     Naperville  United States
4     2011-01-06T00:00:00.000Z  Office Supplies   Philadelphia  United States
...                        ...              ...            ...            ...
9989  2014-12-31T00:00:00.000Z  Office Supplies      Fairfield  United States
9990  2014-12-31T00:00:00.000Z  Office Supplies      Fairfield  United States
9991  2014-12-31T00:00:00.000Z  Office Supplies       Loveland  United States
9992  2014-12-31T00:00:00.000Z  Office Supplies  New York City  United States
9993  2014-12-31T00:00:00.000Z       Technology  New York City  United States

          CustomerName  Discount         OrderID  PostalCode  \
0        Darren Powers       0.2  CA-2011-103800       77095
1        Phillina Ober       0.2  CA-2011-112326       60540
2        Phillina Ober       0.8  CA-2011-112326       60540
3        Phillina Ober       0.2  CA-2011-112326       60540
4           Mick Brown       0.2  CA-2011-141817       19143
...                ...       ...             ...         ...
9989        Erica Bern       0.2  CA-2014-115427       94533
9990        Erica Bern       0.2  CA-2014-115427       94533
9991     Jill Matthias       0.2  CA-2014-156720       80538
9992  Patrick ODonnell       0.2  CA-2014-143259       10009
9993  Patrick ODonnell       0.0  CA-2014-143259       10009

                                            ProductName  Profit  ...  \
0     Message Book, Wirebound, Four 5 1/2 X 4 Forms/...       6  ...
1                                             Avery 508       4  ...
2            GBC Standard Plastic Binding Systems Combs      -5  ...
3                         SAFCO Boltless Steel Shelving     -65  ...
4     Avery Hi-Liter EverBold Pen Style Fluorescent ...       5  ...
...                                                 ...     ...  ...
9989    Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl       5  ...
9990                                 GBC Binding covers       6  ...
9991                                Bagged Rubber Bands      -1  ...
9992               Wilson Jones Legal Size Ring Binders      20  ...
9993                          Gear Head AU3700S Headset       3  ...

      DaystoShipActual SalesForecast     ShipStatus DaystoShipScheduled  \
0                    4            22  Shipped Early                   6
1                    4            15  Shipped Early                   6
2                    4             5  Shipped Early                   6
3                    4           357  Shipped Early                   6
4                    7            26   Shipped Late                   6
...                ...           ...            ...                 ...
9989                 4            18  Shipped Early                   6
9990                 4            27  Shipped Early                   6
9991                 4             4  Shipped Early                   6
9992                 4            69  Shipped Early                   6
9993                 4           119  Shipped Early                   6

     OrderProfitable SalesperCustomer ProfitRatio SalesaboveTarget  latitude  \
0                0.0            16.45        33.8              0.0   29.8941
1                0.0            11.78        36.3              0.0   41.7662
2                0.0             3.54      -155.0              0.0   41.7662
3                0.0           272.74       -23.8              0.0   41.7662
4                0.0            19.54        25.0              0.0   39.9448
...              ...              ...         ...              ...       ...
9989             0.0            13.90        32.5              0.0   38.2671
9990             0.0            20.72        31.3              0.0   38.2671
9991             0.0             3.02       -20.0              0.0   40.4262
9992             0.0            52.78        37.5              0.0   40.7262
9993             0.0            90.93         3.0              0.0   40.7262

      longitude
0      -95.6481
1      -88.1410
2      -88.1410
3      -88.1410
4      -75.2288
...         ...
9989  -122.0357
9990  -122.0357
9991  -105.0900
9992   -73.9796
9993   -73.9796

[9994 rows x 28 columns]

In [20]:
## Filling missing value with mean of the column(any desired column can be used)

# We'll use sales column to fill the missing values with mean of the sales column

df['Sales'].fillna(df['Sales'].mean(), inplace=True)

C:\Users\mamun\AppData\Local\Temp\ipykernel_42036\1476259758.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Sales'].fillna(df['Sales'].mean(), inplace=True)

0        16
1        12
2         4
3       273
4        20
       ...
9989     14
9990     21
9991      3
9992     53
9993     91
Name: Sales, Length: 9994, dtype: int64

In [23]:
## Renaming the columns of the dataset

df.rename(columns={'OrderProfitable':'Profit'}, inplace=True)
df.head(5)

,OrderDate,Category,City,Country,CustomerName,Discount,OrderID,PostalCode,ProductName,Profit,...,DaystoShipActual,SalesForecast,ShipStatus,DaystoShipScheduled,Profit,SalesperCustomer,ProfitRatio,SalesaboveTarget,latitude,longitude
0,2011-01-04T00:00:00.000Z,Office Supplies,Houston,United States,Darren Powers,0.2,CA-2011-103800,77095,"Message Book, Wirebound, Four 5 1/2 X 4 Forms/...",6,...,4,22,Shipped Early,6,NaN,16.45,33.8,NaN,29.8941,-95.6481
1,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.2,CA-2011-112326,60540,Avery 508,4,...,4,15,Shipped Early,6,NaN,11.78,36.3,NaN,41.7662,-88.1410
2,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.8,CA-2011-112326,60540,GBC Standard Plastic Binding Systems Combs,-5,...,4,5,Shipped Early,6,NaN,3.54,-155.0,NaN,41.7662,-88.1410
3,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.2,CA-2011-112326,60540,SAFCO Boltless Steel Shelving,-65,...,4,357,Shipped Early,6,NaN,272.74,-23.8,NaN,41.7662,-88.1410
4,2011-01-06T00:00:00.000Z,Office Supplies,Philadelphia,United States,Mick Brown,0.2,CA-2011-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,5,...,7,26,Shipped Late,6,NaN,19.54,25.0,NaN,39.9448,-75.2288

In [24]:
## Change Datatype of a column

df['NewSalesperCustomer']= df['SalesperCustomer'].astype('int64') # It will change the datatype of the column to int64
df.head(5)

,OrderDate,Category,City,Country,CustomerName,Discount,OrderID,PostalCode,ProductName,Profit,...,SalesForecast,ShipStatus,DaystoShipScheduled,Profit,SalesperCustomer,ProfitRatio,SalesaboveTarget,latitude,longitude,NewSalesperCustomer
0,2011-01-04T00:00:00.000Z,Office Supplies,Houston,United States,Darren Powers,0.2,CA-2011-103800,77095,"Message Book, Wirebound, Four 5 1/2 X 4 Forms/...",6,...,22,Shipped Early,6,NaN,16.45,33.8,NaN,29.8941,-95.6481,16
1,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.2,CA-2011-112326,60540,Avery 508,4,...,15,Shipped Early,6,NaN,11.78,36.3,NaN,41.7662,-88.1410,11
2,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.8,CA-2011-112326,60540,GBC Standard Plastic Binding Systems Combs,-5,...,5,Shipped Early,6,NaN,3.54,-155.0,NaN,41.7662,-88.1410,3
3,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.2,CA-2011-112326,60540,SAFCO Boltless Steel Shelving,-65,...,357,Shipped Early,6,NaN,272.74,-23.8,NaN,41.7662,-88.1410,272
4,2011-01-06T00:00:00.000Z,Office Supplies,Philadelphia,United States,Mick Brown,0.2,CA-2011-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,5,...,26,Shipped Late,6,NaN,19.54,25.0,NaN,39.9448,-75.2288,19

In [29]:
# Data Aggregation and Grouping


grouped_mean= df.groupby('CustomerName')['Discount'].mean() # It will group the data by CustomerName and calculate the mean of the Value column
print(grouped_mean)

CustomerName
Aaron Bergman         0.066667
Aaron Hawkins         0.090909
Aaron Smayling        0.355000
Adam Bellavance       0.044444
Adam Hart             0.135000
                        ...
Xylona Preis          0.046429
Yana Sorensen         0.050000
Yoseph Carroll        0.075000
Zuschuss Carroll      0.254839
Zuschuss Donatelli    0.111111
Name: Discount, Length: 793, dtype: float64

In [33]:
## Aggregate Multiple Functions on a Column

grouped_agg= df.groupby('CustomerName')['Discount'].agg(['mean','sum','max']) # It will group the data by CustomerName and calculate the mean, sum and max of the Value column
print(grouped_agg)

                        mean   sum  max
CustomerName
Aaron Bergman       0.066667  0.40  0.2
Aaron Hawkins       0.090909  1.00  0.2
Aaron Smayling      0.355000  3.55  0.7
Adam Bellavance     0.044444  0.80  0.2
Adam Hart           0.135000  2.70  0.7
...                      ...   ...  ...
Xylona Preis        0.046429  1.30  0.2
Yana Sorensen       0.050000  0.60  0.2
Yoseph Carroll      0.075000  0.60  0.2
Zuschuss Carroll    0.254839  7.90  0.8
Zuschuss Donatelli  0.111111  1.00  0.2

[793 rows x 3 columns]

In [ ]:
# Merging and Joining DataFrames

# Create a sample DataFrame to demonstrate merging and joining

df1 = pd.DataFrame({
    'CustomerID': [1, 2, 3, 4],
    'CustomerName': ['Alice', 'Bob', 'Charlie', 'David'],
    'Country': ['USA', 'Canada', 'UK', 'Australia']
})
df2 = pd.DataFrame({
    'CustomerID': [3, 4, 5, 6],
    'OrderID': [101, 102, 103, 104],
    'OrderAmount': [250, 300, 150, 400]
})

## Merging DataFrames using inner join

merged_inner = pd.merge(df1, df2, on='CustomerID', how='inner')
print("Inner Join Result:")
print(merged_inner)

## Merging DataFrames using left join

merged_left = pd.merge(df1, df2, on='CustomerID', how='left')
print("Left Join Result:")
print(merged_left)

## Mergeing DataFrames using right join 

merged_right = pd.merge(df1, df2, on='CustomerID', how='right')
print("Right Join Result:")
print(merged_right)

## Merging DataFrames using outer join

merged_outer = pd.merge(df1, df2, on='CustomerID', how='outer')
print("Outer Join Result:")
print(merged_outer)

Inner Join Result:
   CustomerID CustomerName    Country  OrderID  OrderAmount
0           3      Charlie         UK      101          250
1           4        David  Australia      102          300
Left Join Result:
   CustomerID CustomerName    Country  OrderID  OrderAmount
0           1        Alice        USA      NaN          NaN
1           2          Bob     Canada      NaN          NaN
2           3      Charlie         UK    101.0        250.0
3           4        David  Australia    102.0        300.0
Right Join Result:
   CustomerID CustomerName    Country  OrderID  OrderAmount
0           3      Charlie         UK      101          250
1           4        David  Australia      102          300
2           5          NaN        NaN      103          150
3           6          NaN        NaN      104          400
Outer Join Result:
   CustomerID CustomerName    Country  OrderID  OrderAmount
0           1        Alice        USA      NaN          NaN
1           2          Bob     Canada      NaN          NaN
2           3      Charlie         UK    101.0        250.0
3           4        David  Australia    102.0        300.0
4           5          NaN        NaN    103.0        150.0
5           6          NaN        NaN    104.0        400.0

## Conclusion
So applying these data manipulation techniques can significantly enhance the quality and usability of data for analysis. By cleaning, transforming, aggregating, and merging data effectively, analysts can derive more accurate insights and make better-informed decisions.